# Generated by Django 4.2.10 on 2024-02-28 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="Nazwa firmy"),
                ),
                (
                    "company_address",
                    models.CharField(max_length=200, verbose_name="Adres firmy"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="Numer telefonu"),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Strona www"),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Firma",
                "verbose_name_plural": "Firmy",
            },
        ),
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Nazwa")),
                ("description", models.TextField(verbose_name="Opis")),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Forma zatrudnienia",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Lokalizacja",
                    ),
                ),
                (
                    "salary_range",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Widełki wynagrodzenia",
                    ),
                ),
                (
                    "posting_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data ogłoszenia"
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data wygaśnięcia"
                    ),
                ),
                (
                    "experience",
                    models.TextField(
                        blank=True, null=True, verbose_name="Oczekiwane doświadczenie"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Stanowisko"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_posts",
                        to="job_posts.company",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ogłoszenie",
                "verbose_name_plural": "Ogłoszenia",
            },
        ),
    ]
