# Generated by Django 4.2.10 on 2024-04-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_posts", "0002_remove_jobpost_salary_range_jobpost_salary_high_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="user",
            new_name="owner",
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="salary_high",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Górna granica wynagrodzenia",
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="salary_low",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Dolna granica wynagrodzenia",
            ),
        ),
    ]
