# Generated by Django 4.2.10 on 2024-04-18 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "job_posts",
            "0003_rename_user_company_owner_alter_jobpost_salary_high_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="jobpost",
            name="owner",
        ),
    ]
