apiVersion: v1
kind: Service
metadata:
  name: azeno-proxy
  namespace: default
  labels:
    app: azeno-proxy
spec:
  type: LoadBalancer
  selector:
    app: azeno-proxy
  ports:
    - name: http
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: azeno-proxy
  namespace: default
  labels:
    app: azeno-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azeno-proxy
  template:
    metadata:
      labels:
        app: azeno-proxy
    spec:
      containers:
        - name: azeno-proxy
          image: "mwasile/azeno-proxy:0.0.2"
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          resources:
            requests:
              memory: "64Mi"
              cpu: "125m"
            limits:
              memory: "256Mi"
              cpu: "250m"