services:
  backend:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - backend/env/.env
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - ./backend:/app
    networks:
      - proxy_backend

networks:
  proxy_backend:
