# Generated by Django 4.2.10 on 2024-04-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_completed_course_price_coursereview"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="agenda",
            field=models.TextField(default="[]", verbose_name="Plan kursu"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
