# Generated by Django 4.2.10 on 2024-04-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_course_is_accepted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrollment",
            options={
                "verbose_name": "Uczestnik kursu",
                "verbose_name_plural": "Uczestnicy kursów",
            },
        ),
    ]
