# Generated by Django 4.2.10 on 2024-04-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_course_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="Link"),
        ),
    ]
