# Generated by Django 4.2.10 on 2024-03-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
