# Generated by Django 4.2.10 on 2024-04-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.FileField(
                blank=True, null=True, upload_to="avatars", verbose_name="Avatar"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(
                blank=True, null=True, verbose_name="Opis użytkownika"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=150, null=True, verbose_name="Imię"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Czy użytkownik ma aktywne konto?",
                verbose_name="Aktywny?",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=150, null=True, verbose_name="Nazwisko"),
        ),
    ]
