# Generated by Django 4.2.5 on 2023-09-30 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_programmepoint_remove_course_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='courses',
            field=models.ManyToManyField(related_name='tags', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='users',
            field=models.ManyToManyField(related_name='tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
