# Generated by Django 4.2.5 on 2023-09-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_tag_courses_alter_tag_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='users',
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(related_name='courses', to='courses.tag'),
        ),
    ]
