# Generated by Django 4.2.5 on 2023-10-01 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_options_project_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses  '},
        ),
        migrations.AlterModelOptions(
            name='learningstages',
            options={'verbose_name': 'Learning stage', 'verbose_name_plural': 'Learning stages'},
        ),
    ]
