# Generated by Django 4.2.10 on 2024-04-16 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0004_course_completed_course_price_coursereview"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Nazwa projektu"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Opis projektu"
                    ),
                ),
                (
                    "source_code_link",
                    models.URLField(blank=True, null=True, verbose_name="Kod źródłowy"),
                ),
                (
                    "live_version_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Link do działającej wersji"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="courses.tag", verbose_name="Tagi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Projekt",
                "verbose_name_plural": "Projekty",
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(upload_to="project_images", verbose_name="Obraz"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="portfolios.project",
                        verbose_name="Projekt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Obraz projektu",
                "verbose_name_plural": "Obrazy projektów",
            },
        ),
    ]
